version: '3.4'
networks:
  backend:
    driver: bridge
  

services:
  rabbit:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: elias
      RABBITMQ_DEFAULT_PASS: pass
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "25672:25672"
      - "15671:15671"
      - "15672:15672"
    networks:
      - backend
  primecalcslave:
    image: ${DOCKER_REGISTRY-}primecalcslave
    build:
      context: .
      dockerfile: PrimeCalcSlave/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    depends_on:
      - rabbit
    networks:
      - backend
    stdin_open: true
    tty: true

  primecalcslave1:
    image: ${DOCKER_REGISTRY-}primecalcslave
    build:
      context: .
      dockerfile: PrimeCalcSlave/Dockerfile
    ports:
      - "8000:80"
      - "8001:443"
    depends_on:
      - rabbit
    networks:
      - backend
    stdin_open: true
    tty: true
